### ISSUE TITLE
Issue with Importing Package in Gradle

### ISSUE THREAD

**Issue by some-dev** [osslabz/evm-abi-decoder#109]
First off, I'd like to say thank you for maintaining such an awesome repository; it's been really helpful!

I'm currently encountering an issue when trying to use the package in a Gradle build. 

I've included the package with the following line in my build file:

`implementation "net.osslabz:evm-abi-decoder:0.0.11"`

![изображение](https://github.com/user-attachments/assets/fc1be43e-8b43-4424-be74-a8ddef9e6860)

The build completes without any errors, but when I attempt to use a class from `net.osslabz.evm.abi` (using for example 
`import net.osslabz.evm.abi.decoder;`), I encounter the following error:

```
error: package net.osslabz.evm.abi does not exist
import net.osslabz.evm.abi.decoder;
```
![изображение](https://github.com/user-attachments/assets/b6674062-7740-48ac-9907-1d5c22651ec0)

It seems like the package isn't being recognized after the build. I've tried cleaning the project and refreshing the Gradle dependencies, but the issue persists.

Any assistance with this issue would be greatly appreciated as i'm primary a .NET developer (so not much Java experience) and probably doing something really dumb here.

Thank you!

**Comment by ronaldoguedess** [comment]
Following

**Comment by some-dev** [comment]
Is there any chance we can grab the attention of @rvullriede  ?  :-)

**Comment by rvullriede** [comment]
There is a reason I still don't use Gradle but prefer good old Maven ;-) Whenever I work with it I encounter strange problems....
However, I was curious and have it a try and it works without any problems. You can find an example here: https://github.com/rvullriede/evm-abi-decoder-gradle-example

**Comment by some-dev** [comment]
Thanks for response and even providing an example!
Let me check it out

**Comment by some-dev** [comment]
looks like indeed the issue was a local setup, once i reinitialized setup  - issue was fixed.
More specifically i rerun `gradle init`, `gradle wrapper`
Thanks again for your help!
