### ISSUE TITLE
[feature]are there any plans to support decodeLog

### ISSUE THREAD

**Issue by whispin** [osslabz/evm-abi-decoder#35]
thanks a lot for your work，solved a lot of my problems，

are there any plans to support decodeLog, just like web3.eth.abi.decodeLog(inputs, hexString, topics);

**Comment by gkozyryatskyy** [comment]
Added log parsing support pull. Please review https://github.com/osslabz/evm-abi-decoder/pull/93

**Comment by rvullriede** [comment]
Please try again with 0.0.11 (available on maven central soon). If it still doesn't work, feel free to reopen again!
