### ISSUE TITLE
maven repo

### ISSUE THREAD

**Issue by llacina** [osslabz/evm-abi-decoder#52]
In maven repo I see only version 0.0.6

**Comment by rvullriede** [comment]
The groupId has changed, please use the following:

```
<dependency>
    <groupId>net.osslabz</groupId>
    <artifactId>evm-abi-decoder</artifactId>
    <version>0.0.7</version>
</dependency>

```

**Comment by llacina** [comment]
I tried this, but 0.0.7 on net.osslabz my project and my browser don't find. @rvullriede

**Comment by rvullriede** [comment]
@llacina, you are absolutely right! I've rolled 0.0.8 now and it's published to maven central: https://repo1.maven.org/maven2/net/osslabz/evm-abi-decoder/

**Comment by llacina** [comment]
@rvullriede thanks :))
