### ISSUE TITLE
Failing to parse ABI

### ISSUE THREAD

**Issue by Anton-To** [osslabz/evm-abi-decoder#61]
Getting exception:
`java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of net.osslabz.evm.abi.definition.AbiDefinition$Entry, problem: Cannot invoke "net.osslabz.evm.abi.definition.AbiDefinition$Entry$Type.ordinal()" because "type" is null`

`[truncated 4967 chars]; line: 16, column: 1] (through reference chain: net.osslabz.evm.abi.definition.AbiDefinition[1])
	at net.osslabz.evm.abi.definition.AbiDefinition.fromJson(AbiDefinition.java:57)`

When trying to parse the following contract abi: https://api-testnet.bscscan.com/api?module=contract&action=getabi&address=0xb7564227245bb161ebf4d350e1056c26801f1366&format=raw

removing the following part of the json results in it being parsed properly
` {
  "inputs": [],
  "name": "InvalidShortString",
  "type": "error"
}, {
  "inputs": [
    {
      "internalType": "string",
      "name": "str",
      "type": "string"
    }
  ],
  "name": "StringTooLong",
  "type": "error"
},`

**Comment by vhordiienko-hacken** [comment]
I got the same issue. I tried to add enum Type "error" but still problem exists. 
Need help
