### ISSUE TITLE
not works

### ISSUE THREAD

**Issue by ronaldoguedess** [osslabz/evm-abi-decoder#85]
FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform jackson-core-2.16.1.jar (com.fasterxml.jackson.core:jackson-core:2.16.1) to match attributes {artifactType=android-jni, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\ronaldo\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.16.1\9456bb3cdd0f79f91a5f730a1b1bb041a380c91f\jackson-core-2.16.1.jar.
         > Failed to transform 'C:\Users\ronaldo\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.16.1\9456bb3cdd0f79f91a5f730a1b1bb041a380c91f\jackson-core-2.16.1.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 65. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

**Comment by rvullriede** [comment]
Are you sure you're reporting this in the right repo? I don't see anything related to this lib in your error output.

**Comment by ronaldoguedess** [comment]
yeah, i'm reporting because i can't use, haha
when import lib shows this error!

**Comment by ronaldoguedess** [comment]
Don't you have to update the version of this lib for me update?

**Comment by rvullriede** [comment]
I rather prefer you validate first that the branch fixes the issue before I build a new release. You simply need to check out out and install locally (`maven clean install`) and have you local maven repository listed in you gradle file.

**Comment by rvullriede** [comment]
Please try again with 0.0.11 (available on maven central soon). If it still doesn't work, feel free to reopen again!
