### ISSUE TITLE
tuple[] and log parsing support

### ISSUE THREAD

**Issue by gkozyryatskyy** [osslabz/evm-abi-decoder#94]
Hello! 
Thank you for a great repo.
Please review and merge if possible https://github.com/osslabz/evm-abi-decoder/pull/93

**Comment by rvullriede** [comment]
@gkozyryatskyy , thanks for your contribution! I had to re-work it a bit a re-enable Java 8 for android compatibility :-( I'll revisit this later again.
This has been merged and released as 0.0.11 (available on maven central soon).

**Comment by gkozyryatskyy** [comment]
@rvullriede Thank you!
